/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation;

import java.awt.Dimension;
import java.awt.Toolkit;
import Data_Access_Object.DataBase;

/**
 *
 * @author root
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    DataBase db;
    OperationForm operationForm;
    ClientForm clientForm;
    BookForm bookForm;
    
    public Home() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 -getWidth()/2, size.height/2 - getHeight()/2 );
        db = new DataBase();
        operationForm = new OperationForm();
        clientForm = new ClientForm();
        bookForm = new BookForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        OperationMenuBar = new javax.swing.JMenu();
        OperationMenu = new javax.swing.JMenuItem();
        settingMenuBar = new javax.swing.JMenu();
        ClientMenu = new javax.swing.JMenuItem();
        BookMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        Desktop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        OperationMenuBar.setMnemonic('O');
        OperationMenuBar.setText("Operations");
        OperationMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationMenuBarActionPerformed(evt);
            }
        });

        OperationMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OperationMenu.setText("Operation");
        OperationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationMenuActionPerformed(evt);
            }
        });
        OperationMenuBar.add(OperationMenu);

        jMenuBar1.add(OperationMenuBar);

        settingMenuBar.setMnemonic('S');
        settingMenuBar.setText("Setting");

        ClientMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        ClientMenu.setText("Client");
        ClientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientMenuActionPerformed(evt);
            }
        });
        settingMenuBar.add(ClientMenu);

        BookMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        BookMenu.setText("Book");
        BookMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookMenuActionPerformed(evt);
            }
        });
        settingMenuBar.add(BookMenu);

        jMenuBar1.add(settingMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationMenuActionPerformed
        // TODO add your handling code here:
        Desktop.add(operationForm);
        operationForm.show();

          
    }//GEN-LAST:event_OperationMenuActionPerformed

    private void OperationMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationMenuBarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OperationMenuBarActionPerformed

    private void ClientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuActionPerformed
        // TODO add your handling code here:
        Desktop.add(clientForm);
        clientForm.show();
    }//GEN-LAST:event_ClientMenuActionPerformed

    private void BookMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookMenuActionPerformed
        // TODO add your handling code here:
        Desktop.add(bookForm);
        bookForm.show();
    }//GEN-LAST:event_BookMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BookMenu;
    private javax.swing.JMenuItem ClientMenu;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem OperationMenu;
    private javax.swing.JMenu OperationMenuBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu settingMenuBar;
    // End of variables declaration//GEN-END:variables
}
