package Model;
// Generated May 10, 2020 1:12:19 PM by Hibernate Tools 3.6.0



/**
 * BookCategorie generated by hbm2java
 */
public class BookCategorie  implements java.io.Serializable {


     private String categorieId;
     private String categorieName;

    public BookCategorie() {
    }

    public BookCategorie(String categorieId, String categorieName) {
       this.categorieId = categorieId;
       this.categorieName = categorieName;
    }
   
    public String getCategorieId() {
        return this.categorieId;
    }
    
    public void setCategorieId(String categorieId) {
        this.categorieId = categorieId;
    }
    public String getCategorieName() {
        return this.categorieName;
    }
    
    public void setCategorieName(String categorieName) {
        this.categorieName = categorieName;
    }




}


