package Model;
// Generated May 10, 2020 1:12:19 PM by Hibernate Tools 3.6.0



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String regNo;
     private String firstName;
     private String lastName;
     private String phoneNo;
     private String email;
     private String status;
     private String photo;

    public Client() {
    }

	
    public Client(String regNo, String firstName, String lastName, String status) {
        this.regNo = regNo;
        this.firstName = firstName;
        this.lastName = lastName;
        this.status = status;
    }
    public Client(String regNo, String firstName, String lastName, String phoneNo, String email, String status, String photo) {
       this.regNo = regNo;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNo = phoneNo;
       this.email = email;
       this.status = status;
       this.photo = photo;
    }
   
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


