package Model;
// Generated May 10, 2020 1:12:19 PM by Hibernate Tools 3.6.0



/**
 * WithDrowBook generated by hbm2java
 */
public class WithDrowBook  implements java.io.Serializable {


     private String bookName;
     private String clientName;
     private String status;
     private String dates;

    public WithDrowBook() {
    }

	
    public WithDrowBook(String bookName, String clientName, String status) {
        this.bookName = bookName;
        this.clientName = clientName;
        this.status = status;
    }
    public WithDrowBook(String bookName, String clientName, String status, String dates) {
       this.bookName = bookName;
       this.clientName = clientName;
       this.status = status;
       this.dates = dates;
    }
   
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDates() {
        return this.dates;
    }
    
    public void setDates(String dates) {
        this.dates = dates;
    }




}


